name: mock-transactions pull request check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  pr-check:
    name: PR Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Gradle repository
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: build
        run: gradle detekt build